; RASharp 示例配置
-常用(&App)
记事本(&N)|notepad.exe
计算器(&C)|calc.exe
--系统工具
命令提示符|cmd.exe
Everything搜索|Everything.exe
-网址(&Web)
百度(&B)	!b|https://www.baidu.com/s?wd=%s
-输入(&Input)
示例邮箱:*:mail|name@example.com;
当前时间|%A_YYYY%-%A_MM%-%A_DD% %A_Hour%:%A_Min%:%A_Sec%;
